version: "3"

services:
    mobile:
        container_name: mobile
        restart: always
        build: .
        ports: 
            - "5050:5050"
        environment:
            - TZ=America/La_Paz
        volumes:
            - .:/usr/src/app